### ISSUE TITLE
Add important game-related information to the top of the Moderator Events log

### ISSUE THREAD

**Issue by IndexLibrorumProhibitorum** [magge-faf/faf-moderator-client-develop-modified#38]
Information such as whether a game is ranked, whether a game is on full-share, partial-share, or no-share, and whether cheating was turned on is rather useful to handle reports. 

As it is now, while I can confirm that a player Ctrl-K'd their units, I will have to check through the FAF client to see if this happened in a full-share game, since doing this in a no-share game is not technically against the rules.
This information is present in the replay information, so it shouldn't be too much effort to add this in.

**Comment by magge-faf** [comment]
@IndexLibrorumProhibitorum Anything that I should change/add/remove that is important for the moderation process?

If cheats were enabled, it will show it in the first line in the chat log with an !-indicator, otherwise I ignore it to avoid text noise:

```
        if (Boolean.parseBoolean(cheatsEnabled)) {
            report.append("[!] Cheats Enabled: ").append(cheatsEnabled).append("\n");
        }
```

same for non-default values for Common Army (If you remember our union-control-thing recently ...)

![image](https://github.com/magge-faf/faf-moderator-client-develop-modified/assets/101107758/89002f57-9912-4b72-8142-c9913d8398d1)

![image](https://github.com/magge-faf/faf-moderator-client-develop-modified/assets/101107758/4f9569d4-aa92-489b-bb11-8d58769e7ec8)

![image](https://github.com/magge-faf/faf-moderator-client-develop-modified/assets/101107758/44733404-4b35-4e8a-8a59-c4f8ccaee3f0)

**Comment by IndexLibrorumProhibitorum** [comment]
Looks good and complete! I like the [!] indicator. All 3 screenshots show team 2 and 3 rather than team 1 and 2, is that intentional?

**Comment by magge-faf** [comment]
Thanks - Yes, that is from the replay-data itself. TMK Team 1 are spectators, and Team 0 are civilians (or vice versa?). That is just how it is treated within the replay.
